sudo: required

matrix:
      
services:
  - docker

env:

script:
  - echo ' -----------------  TEST PART 1 ----------------- '
  - docker ps -a 
  - dokcer images 
  - docker run --rm -v $PWD/analysis:/url  yennanliu/mac_ds_ml_env:v1 /bin/bash -c "git clone https://github.com/yennanliu/analysis.git ;  ls  ;  pwd ; python analysis/ml_demo.py"