
sudo: required

matrix:
      
services:
  - docker

env:

before_install:

install:

before_script: 

script:
  - echo ' -----------------  BUILD PART 1 ----------------- '
  - echo REGISTRY_USER = $REGISTRY_USER && echo REGISTRY_PASS = $REGISTRY_PASS
  #- echo 'docker bulid...' && cd mac_de_docker && pwd && ls  && docker build -f Dockerfile .
  - echo 'docker bulid...' && docker build -f mac_de_docker/Dockerfile .
  #- docker run -it $image_id echo 'docker test 123'
  - docker run -it jupyter/scipy-notebook echo 'docker test 123'
  - container_id="` docker ps -a | awk 'FNR == 2 {print $1}'`" && echo container_id = $container_id && image_id="` docker ps -a | awk 'FNR == 2 {print $2}'`" && echo image_id = $image_id 
  - docker ps -a 
  - docker images

after_script:  

after_success:

after_failure:

before_deploy:

deploy:


after_deploy:


